version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: meritmony
    container_name: meritmony
    restart: unless-stopped
    ports: 
        - "3000:3000"
